name: eShopOnWeb Build and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      run: | 
        dotnet build ./eShopOnWeb.sln --configuration Release
        dotnet publish -c Release -o myapp 
    
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: sample-dotnet-core-webapp
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        package: './myapp'
