name: Github Actions test

on:
  push:
    branches:
      - main
      - develop
      - qa
      - release/*
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
      - qa
      - feature/*
  workflow_dispatch:

env:
  WEBAPP_NAME: sample-dotnet-core-webapp
  WEBAPP_PACKAGE_PATH: '.'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: 'Output the branch'
      run: |
         echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
         cat $GITHUB_ENV
         echo "action_state=yellow" >> $GITHUB_ENV
         echo "This is the ${{ env.BRANCH }}"
         echo "This is the colour ${{ env.action_state }}"
         env
   
    - name: 'Condition for main'
      if: env.BRANCH == 'main'
      run: echo "Passed with the BRANCH"
      
    - name: 'Condition for release'
      if: env.BRANCH == 'release'
      run: echo "Passed with the BRANCH"
