name: Github Actions test

on:
  push:
    branches:
      - main
      - develop
      - qa
      - release/*
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
      - qa
      - feature/*
  workflow_dispatch:

env:
  WEBAPP_NAME: sample-dotnet-core-webapp
  WEBAPP_PACKAGE_PATH: '.'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: 'Output the branch'
      run: |
         echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
         echo "This is the ${BRANCH}"
         env
   
    - name: 'Condition success'
      if: contains('main', github.ref)
      run: echo "Passed with ${BRANCH}"
