name: eShopOnWeb Build and Test

on: [push, pull_request, workflow_dispatch]

env:
  WEBAPP_NAME: sample-dotnet-core-app
  WEBAPP_PACKAGE_PATH: '.'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: dotnet publish
      run: |
        dotnet publish -c Release -o dotnetcorewebapp 
    
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WEBAPP_NAME }}
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        package: '${{ env.WEBAPP_PACKAGE_PATH }}/myapp'
