name: eShopOnWeb Build and Test

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'services/account_engine'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'services/account_engine'
    branches:
      - master
      - develop
      - feature/*
  workflow_dispatch:

env:
  WEBAPP_NAME: sample-dotnet-core-webapp
  WEBAPP_PACKAGE_PATH: '.'

jobs:
  prod-check:
      if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      steps:
        - run: echo "Deploying to production server on branch $GITHUB_REF"
  dev-check:
      if: github.ref == 'refs/heads/develop'
      runs-on: ubuntu-latest
      steps:
        - run: echo "Deploying to production server on branch $GITHUB_REF"
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    - name: dotnet publish
      run: |
        dotnet publish eShopOnWeb.sln -c release -o eShopOnWebapp
      
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WEBAPP_NAME }}
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        package: './eShopOnWebapp'
