name: eShopOnWeb Build and Test

on: [push, pull_request, workflow_dispatch]

env:
  WEBAPP_NAME: sample-dotnet-core-webapp
  WEBAPP_PACKAGE_PATH: '.'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WEBAPP_NAME }}
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        package: '${{ env.WEBAPP_PACKAGE_PATH }}/eShopOnWeb/'
